name: Test

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-projectname-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-projectname-

    - name: Install node modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Should pass linting
      run: npm run lint

    - name: Should pass unit test
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

    - name: Should succeed source building
      run: npm run build-storybook
